Models/Alumno.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escuelita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public int id_alumno { get; set; }
        public string nombre_alumno { get; set; }
        public string apellido_alumno { get; set; }
        public string matricula_alumno { get; set; }
        public Nullable<bool> ingles_materia { get; set; }
        public Nullable<bool> espanol_materia { get; set; }
        public Nullable<bool> matematicas_materia { get; set; }
        public Nullable<bool> ciencias_materia { get; set; }
    }
}

Models/ViewModels/AlumnoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Escuelita.Models.ViewModels
{
    public class AlumnoViewModel
    {
        public int Id_Alumno { get; set; }
        [Required]
        [Display(Name ="Nombre")]
        public string Nombre_Alumno { get; set; }
        [Required]
        [Display(Name = "Apellido")]
        public string Apellido_Alumno { get; set; }
        [Required]
        [Display(Name = "Matricula")]
        public string Matricula { get; set; }
        [Display(Name = "Ingles")]
        public bool Ingles { get; set; }

        [Display(Name = "Español")]
        public bool Espanol { get; set; }

        [Display(Name = "Matematicas")]
        public bool Matematicas { get; set; }

        [Display(Name = "Ciencias")]
        public bool Ciencias { get; set; }
    }
}

Models/ViewModels/AlumnosViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Escuelita.Models.ViewModels
{
    public class AlumnosViewModel
    {
        public int Id_Alumno { get; set; }
        [Required]
        [Display(Name ="Nombre")]
        public string Nombre_Alumno { get; set; }
        [Required]
        [Display(Name = "Apellido")]
        public string Apellido_Alumno { get; set; }
        [Required]
        [Display(Name = "Matricula")]
        public string Matricula { get; set; }
        [Display(Name = "Ingles")]
        public bool Ingles { get; set; }

        [Display(Name = "Español")]
        public bool Espanol { get; set; }

        [Display(Name = "Matematicas")]
        public bool Matematicas { get; set; }

        [Display(Name = "Ciencias")]
        public bool Ciencias { get; set; }
    }
}

Controllers/AlumnosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Escuelita.Models;
using Escuelita.Models.ViewModels;

namespace Escuelita.Controllers
{
    public class AlumnosController : Controller
    {
        // ++++++++++++ TABLA ALUMNOS ++++++++++++ //
        #region Tabla alumnos
        public ActionResult Index()
        {
            List<ListaAlumnoViewModel> lst;
            using (SchoolEntities db = new SchoolEntities())
            {
                lst = (from d in db.Alumnos
                       select new ListaAlumnoViewModel
                       {
                           Id_Alumno = d.id_alumno,
                           Nombre_Alumno = d.nombre_alumno,
                           Apellido_Alumno = d.apellido_alumno,
                           Matricula = d.matricula_alumno
                       }).ToList();
            }
            return View(lst);
        }
        #endregion

        // ++++++++++++ CREAR ALUMNOS ++++++++++++ //
        #region Crear Alumnos
        public ActionResult Nuevo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Nuevo(AlumnoViewModel model, string InglesM, string EspanolM, string MatematicasM, string CienciasM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (SchoolEntities db = new SchoolEntities())
                    {
                        var oAlumnos = new Alumno();
                        oAlumnos.nombre_alumno = model.Nombre_Alumno;
                        oAlumnos.apellido_alumno = model.Apellido_Alumno;
                        oAlumnos.matricula_alumno = model.Matricula;

                        if (InglesM == "true")
                        {
                            oAlumnos.ingles_materia = model.Ingles == false;
                        }
                        else
                        {
                            oAlumnos.ingles_materia = model.Ingles == true;
                        }

                        if (EspanolM == "true")
                        {
                            oAlumnos.espanol_materia = model.Espanol == false;
                        }
                        else
                        {
                            oAlumnos.espanol_materia = model.Espanol == true;
                        }
                        if (MatematicasM == "true")
                        {
                            oAlumnos.matematicas_materia = model.Matematicas == false;
                        }
                        else
                        {
                            oAlumnos.matematicas_materia = model.Matematicas == true;
                        }
                        if (CienciasM == "true")
                        {
                            oAlumnos.ciencias_materia = model.Ciencias == false;
                        }
                        else
                        {
                            oAlumnos.ciencias_materia = model.Ciencias == true;
                        }


                        db.Alumnos.Add(oAlumnos);
                        db.SaveChanges();
                    }

                    TempData["success"] = "¡El alumno se ha creado con éxito!.";
                    return Redirect("~/Alumnos");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
        #endregion

        // ++++++++++++ EDITAR ALUMNOS ++++++++++++ //
        #region Editar Alumnos
        public ActionResult Editar(int id)
        {
            AlumnoViewModel model = new AlumnoViewModel();
            using (SchoolEntities db = new SchoolEntities())
            {
                var oAlumno = db.Alumnos.Find(id);
                model.Nombre_Alumno = oAlumno.nombre_alumno;
                model.Apellido_Alumno = oAlumno.apellido_alumno;
                model.Matricula = oAlumno.matricula_alumno;
                model.Id_Alumno = oAlumno.id_alumno;
                model.Ingles = oAlumno.ingles_materia ?? false;
                model.Matematicas = oAlumno.matematicas_materia ?? false;
                model.Espanol = oAlumno.espanol_materia ?? false;
                model.Ciencias = oAlumno.ciencias_materia ?? false;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Editar(AlumnoViewModel model, string InglesM, string EspanolM, string MatematicasM, string CienciasM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (SchoolEntities db = new SchoolEntities())
                    {
                        var oAlumno = db.Alumnos.Find(model.Id_Alumno);
                        oAlumno.nombre_alumno = model.Nombre_Alumno;
                        oAlumno.apellido_alumno = model.Apellido_Alumno;
                        oAlumno.matricula_alumno = model.Matricula;


                        if (InglesM == "true")
                        {
                            oAlumno.ingles_materia = model.Ingles == false;
                        }
                        else
                        {
                            oAlumno.ingles_materia = model.Ingles == true;
                        }

                        if (EspanolM == "true")
                        {
                            oAlumno.espanol_materia = model.Espanol == false;
                        }
                        else
                        {
                            oAlumno.espanol_materia = model.Espanol == true;
                        }
                        if (MatematicasM == "true")
                        {
                            oAlumno.matematicas_materia = model.Matematicas == false;
                        }
                        else
                        {
                            oAlumno.matematicas_materia = model.Matematicas == true;
                        }
                        if (CienciasM == "true")
                        {
                            oAlumno.ciencias_materia = model.Ciencias == false;
                        }
                        else
                        {
                            oAlumno.ciencias_materia = model.Ciencias == true;
                        }


                        db.Entry(oAlumno).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                    TempData["EditSuccess"] = "¡El alumno ha sido editado!.";
                    return Redirect("~/Alumnos");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
        #endregion

        // ++++++++++++ ELIMINAR ALUMNOS ++++++++++++ //
        #region Eliminar Alumnos
        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            AlumnoViewModel model = new AlumnoViewModel();
            using (SchoolEntities db = new SchoolEntities())
            {
                var oAlumno = db.Alumnos.Find(id);
                db.Alumnos.Remove(oAlumno);
                db.SaveChanges();
            }
            TempData["DeleteSuccess"] = "¡El alumno ha sido con éxito!.";
            return Redirect("~/Alumnos");
        }
        #endregion

        // ++++++++++++ ASIGNAR MATERAS A ALUMNOS ++++++++++++ //
        #region Asignar Materias Alumnos
        private SchoolEntities objSchoolEntities;
        public AlumnosController()
        {
            objSchoolEntities = new SchoolEntities();
        }

        public ActionResult AsignarMateriasAlumnos()
        {
            AlumnoMateriaViewModel objMateriaViewModel = new AlumnoMateriaViewModel()
            {
                ListaAlumnos = (from objAlumnos in objSchoolEntities.Alumnos
                                select new SelectListItem()
                                {
                                    Text = objAlumnos.nombre_alumno,
                                    Value = objAlumnos.id_alumno.ToString()
                                }).ToList(),
                ListaMaterias = (from objMaterias in objSchoolEntities.Materias
                                 select new ListaAlumnoMateriaViewModel()
                                 {
                                     id_materia = objMaterias.id_materia,
                                     materia = objMaterias.materia_nombre,
                                     IsSelected = false
                                 }).ToList()
            };
            return View(objMateriaViewModel);
        }

        [HttpPost]
        public JsonResult AsignarMateriasAlumnos(int id_alumno, List<int> ListaMateriasId)
        {
            if (objSchoolEntities.AlumnoMaterias.Any(model => model.alumno_id == id_alumno))
            {
                objSchoolEntities.AlumnoMaterias.RemoveRange(
                    objSchoolEntities.AlumnoMaterias.Where(model => model.alumno_id == id_alumno));
                objSchoolEntities.SaveChanges();
            }
            foreach (var item in ListaMateriasId)
            {
                AlumnoMateria objAlumnoMateria = new AlumnoMateria();
                objAlumnoMateria.alumno_id = id_alumno;
                objAlumnoMateria.materia_id = item;
                objSchoolEntities.AlumnoMaterias.Add(objAlumnoMateria);
                objSchoolEntities.SaveChanges();
            }
            return Json(new { success = true, message = "Se asignaron correctamente las mateias!" }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Vista parcial para las materias de los alumnos en la vista AsignarMateria
        /// </summary>
        public ActionResult TablaAlumnoMaterias()
        {

Views/Alumnos/AsignarMateriasAlumnos.cshtml
@model Escuelita.Models.ViewModels.AlumnoMateriaViewModel
@{
    ViewBag.Title = "AsignarMateriasAlumnos";
}

<h2>Asignar Materias a Alumnos</h2>

@using (Html.BeginForm("AsignarMateriasAlumnos", "Alumnos", FormMethod.Post))
{
    <div class="container">
        <div class="row">
            <div class="form-group">
                @Html.LabelFor(model => model.id_NombreAlumno, new { @class = "control-label" })
                @Html.DropDownListFor(model => model.id_NombreAlumno, Model.ListaAlumnos, new { @class = "form-control", @id = "idAlumno" })
            </div>
        </div>
        <div class="row">
            <div class="form-group">
                @Html.LabelFor(model => model.id_NombreMateria, new { @class = "control-label" })
                <br />
                <table style="width:100%" id="tablaMaterias">
                    @foreach (var item in Model.ListaMaterias)
                    {
                        <tr>
                            <td>
                                <input type="checkbox" name="@item.materia" value="@item.id_materia" checked="@item.IsSelected" /> @item.materia
                            </td>
                        </tr>
                    }
                </table>

                <div>
                    <br />
                    <input type="button" value="Guardar" name="Save" id="btnGuardar" class="btn btn-primary" />
                </div>

            </div>
        </div>
        
    </div>
}

<div>
    @{
        Html.RenderAction("TablaAlumnoMaterias", "Alumnos");
    }
</div>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#btnGuardar").click(function () {
            AsignarMateriasAlumnos();
        });
    });

    function AsignarMateriasAlumnos() {

        var ListaMateriasId = [];

        $.each($("#tablaMaterias input[type=checkbox]:checked"),
            function (index, data) {
                if (data.checked === true) {

                    //var id_materia = $(this).val();
                    //var materia = $(this).attr('name');
                    //alert(id_materia + " " + materia);

                    ListaMateriasId.push($(this).val());
                }
            });

        $.ajax({
            async: true,
            type: 'POST',
            dataType: 'json',
            contentType: 'application/json; charset=uft-8',
            url: '/Alumnos/AsignarMateriasAlumnos',
            data: JSON.stringify({ id_alumno: $("#idAlumno").val(), ListaMateriasId: ListaMateriasId }),
            success: function (data) {
                debugger;
                if (data.success === true) {
                    alert(data.message);
                    ResetCheckbox()
                }
            },
            error: function () {
                alert('Hay un problema para procesar tu solicitud.')
            }
        });
    }

    function ResetCheckbox() {
        $.each($("#tablaMaterias input[type=checkbox]:checked"),
            function (index, data) {
                if (data.checked === true) {
                    $(this).prop('checked', false);
                }
            });
        $("#idAlumno").val(1)
    }
</script>

Views/Alumnos/Editar.cshtml
@model Escuelita.Models.ViewModels.AlumnoViewModel
@{
    ViewBag.Title = "Editar Alumno";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Editar", "Alumnos", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            @Html.HiddenFor(d => d.Id_Alumno)
            <div>
                @Html.LabelFor(d => d.Nombre_Alumno)
                @Html.TextBoxFor(d => d.Nombre_Alumno, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Nombre_Alumno, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.Apellido_Alumno)
                @Html.TextBoxFor(d => d.Apellido_Alumno, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Apellido_Alumno, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.Matricula)
                @Html.TextBoxFor(d => d.Matricula, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Matricula, null, new { @class = "red" })
            </div>

            <div class="form-group">
                <label>Materias</label>
                <div>
                    <label class="checkbox-inline">
                        @Html.CheckBoxFor(d => d.Ingles)
                        Ingles
                    </label>
                    <label class="checkbox-inline">
                        @Html.CheckBoxFor(d => d.Espanol)
                        Español
                    </label>
                    <label class="checkbox-inline">
                        @Html.CheckBoxFor(d => d.Matematicas)
                        Matematicas
                    </label>
                    <label class="checkbox-inline">
                        @Html.CheckBoxFor(d => d.Ciencias)
                        Ciencias
                    </label>
                </div>
            </div>

            <div style="text-align:right">
                @Html.ActionLink("Regresar", "Index", "Alumnos", null, new { @class = "btn btn-primary", @style = "text-align:right" })
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

Views/Alumnos/Index.cshtml
@model List<Escuelita.Models.ViewModels.ListaAlumnoViewModel>

@{
    ViewBag.Title = "Lista de Alumnos";
}

<br />
@if (TempData["Success"] != null)
{
    <p class="alert alert-success" id="successMessage">
        @TempData["Success"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </p>
}

@if (TempData["EditSuccess"] != null)
{
    <p class="alert alert-info" id="successMessage">
        @TempData["EditSuccess"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </p>
}

@if (TempData["DeleteSuccess"] != null)
{
    <p class="alert alert-danger" id="successMessage">
        @TempData["DeleteSuccess"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </p>
}

<h2>@ViewBag.Title</h2>

<div class="row" style="padding:10px">
    <a href="~/Alumnos/Nuevo" class="btn btn-primary">Crear Alumno</a>
</div>
<br />
<table class="table">
    <tr>
        <th>
            Nombre
        </th>
        <th>
            Apellido
        </th>
        <th>
            Matricula
        </th>
        <th>Acciones</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.Nombre_Alumno
            </td>
            <td>
                @item.Apellido_Alumno
            </td>
            <td>
                @item.Matricula
            <td>
                <a class="btn btn-default" href="~/Alumnos/Editar/@item.Id_Alumno">Editar</a>
                <a class="btn btn-danger" href="~/Alumnos/Eliminar/@item.Id_Alumno">Eliminar</a>
            </td>
        </tr>
    }

</table>

Views/Alumnos/Nuevo.cshtml
@model Escuelita.Models.ViewModels.AlumnoViewModel
@{
    ViewBag.Title = "Crear Alumno";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Nuevo", "Alumnos", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
            <div>
                @Html.LabelFor(d => d.Nombre_Alumno)
                @Html.TextBoxFor(d => d.Nombre_Alumno, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Nombre_Alumno, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.Apellido_Alumno)
                @Html.TextBoxFor(d => d.Apellido_Alumno, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Apellido_Alumno, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.Matricula)
                @Html.TextBoxFor(d => d.Matricula, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Matricula, null, new { @class = "red" })
            </div>
            <div class="form-group">                
                <label>Materias</label>
                <div>
                    <label class="checkbox-inline">
                        @Html.CheckBox("InglesM", false)
                        Ingles
                    </label>
                    <label class="checkbox-inline">
                        @Html.CheckBox("EspanolM", false)
                        Español
                    </label>
                    <label class="checkbox-inline">
                        @Html.CheckBox("MatematicasM", false)
                        Matematicas
                    </label>
                    <label class="checkbox-inline">
                        @Html.CheckBox("CienciasM", false)
                        Ciencias
                    </label>
                </div>
            </div>
        </div>


        <div style="text-align:right">
            @Html.ActionLink("Regresar", "Index", "Alumnos", null, new { @class = "btn btn-primary", @style = "text-align:right" })
            <input type="submit" value="Guardar" class="btn btn-success" />
        </div>
    </div>


}

Views/Alumnos/TablaAlumnoMaterias.cshtml
@model List<Escuelita.Models.ViewModels.ListaAlumnoViewModel>

@{ 
    Layout = "";
}

<br />

<table class="table">
    <tr>
        <th>
            Nombre
        </th>
        <th>
            Apellido
        </th>
        <th>
            Matricula
        </th>
        <th>
            Materias
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.Nombre_Alumno
            </td>
            <td>
                @item.Apellido_Alumno
            </td>
            <td>
                @item.Matricula
            <td>
                @item.Materia_Nombre
            </td>
        </tr>
    }
</table>